export { Onboarding, TermsAndCondition, LanguageSelection } from './Auth';
export {
  Welcome,
  Home,
  EMI,
  LoanEligibility,
  CompareLoans,
  TaxCalculation,
  SWP,
  SIP,
  EquityLinkedScheme,
  Lumpsum,
  FixedDeposit,
  RecurringDeposit,
  PublicProvidentFund,
  SimpleAndCompound,
  CurrencyConversion,
  DiscountCalculator,
  PriceCalculator,
  MarginCalculator,
  MarkupCalculator,
  OperatingMargin,
  MarginWithSales,
  BankFinder,
  ATMFinder,
  Theory,
  FAQ,
} from './App';
