const ImagePath = '../Assets/Images/';
const png = '.png';

const Images = {
  True: require(ImagePath + 'True' + png),
  onboarding_0: require(ImagePath + 'onboarding_0' + png),
  onboarding_1: require(ImagePath + 'onboarding_1' + png),
  onboarding_2: require(ImagePath + 'onboarding_2' + png),
  Announcing: require(ImagePath + 'Announcing' + png),
  Notice: require(ImagePath + 'Notice' + png),
  OurPromise: require(ImagePath + 'OurPromise' + png),
  Safeguard: require(ImagePath + 'Safeguard' + png),
  Terms: require(ImagePath + 'Terms' + png),
  Afrikaans: require(ImagePath + 'Afrikaans' + png),
  Arabic: require(ImagePath + 'Arabic' + png),
  Bengali: require(ImagePath + 'Bengali' + png),
  Chinese: require(ImagePath + 'Chinese' + png),
  Danish: require(ImagePath + 'Danish' + png),
  Dutch: require(ImagePath + 'Dutch' + png),
  Filipino: require(ImagePath + 'Filipino' + png),
  US: require(ImagePath + 'US' + png),
  Logo: require(ImagePath + 'Logo' + png),
  PrivacyPolicy: require(ImagePath + 'PrivacyPolicy' + png),
  InviteFriends: require(ImagePath + 'InviteFriends' + png),
  RateUs: require(ImagePath + 'RateUs' + png),
  Back: require(ImagePath + 'Back' + png),
  Drawer: require(ImagePath + 'Drawer' + png),
  Home: require(ImagePath + 'Home' + png),
  AboutUs: require(ImagePath + 'AboutUs' + png),
  EmiCalculator: require(ImagePath + 'EmiCalculator' + png),

  AllCalculatorTheory: require(ImagePath + 'AllCalculatorTheory' + png),
  ATMFinder: require(ImagePath + 'ATMFinder' + png),
  BankFinder: require(ImagePath + 'BankFinder' + png),
  CompareLoans: require(ImagePath + 'CompareLoans' + png),
  CurrencyConversion: require(ImagePath + 'CurrencyConversion' + png),
  Discount: require(ImagePath + 'Discount' + png),
  ELS: require(ImagePath + 'ELS' + png),
  FAQ: require(ImagePath + 'FAQ' + png),
  FixedDeposit: require(ImagePath + 'FixedDeposit' + png),
  LoanEligibility: require(ImagePath + 'LoanEligibility' + png),
  LumpsumCalculator: require(ImagePath + 'LumpsumCalculator' + png),
  Margin: require(ImagePath + 'Margin' + png),
  MarginWithSales: require(ImagePath + 'MarginWithSales' + png),
  Markup: require(ImagePath + 'Markup' + png),
  OperatingMargin: require(ImagePath + 'OperatingMargin' + png),
  Price: require(ImagePath + 'Price' + png),
  PublicProvidentFund: require(ImagePath + 'PublicProvidentFund' + png),
  RecurringDeposit: require(ImagePath + 'RecurringDeposit' + png),
  SimpleCompound: require(ImagePath + 'SimpleCompound' + png),
  SIP: require(ImagePath + 'SIP' + png),
  SWP: require(ImagePath + 'SWP' + png),
  TaxCalculation: require(ImagePath + 'TaxCalculation' + png),
  Calendar: require(ImagePath + 'Calendar' + png),
  ArrowRightShift: require(ImagePath + 'ArrowRightShift' + png),

  Bank_Accounting: require(ImagePath + 'Bank_Accounting' + png),
  Bank_Auditing: require(ImagePath + 'Bank_Auditing' + png),
  Bank_CompareLoans: require(ImagePath + 'Bank_CompareLoans' + png),
  Bank_CreditCardPayOff: require(ImagePath + 'Bank_CreditCardPayOff' + png),
  Bank_FD: require(ImagePath + 'Bank_FD' + png),
  Bank_RD: require(ImagePath + 'Bank_RD' + png),
  Bank_LoanEligibility: require(ImagePath + 'Bank_LoanEligibility' + png),
  Bank_Loans: require(ImagePath + 'Bank_Loans' + png),
  Bank_LoanToDepositeRatio: require(ImagePath +
    'Bank_LoanToDepositeRatio' +
    png),
  Bank_Saving: require(ImagePath + 'Bank_Saving' + png),
  Bank_TypesOfBanks: require(ImagePath + 'Bank_TypesOfBanks' + png),

  Finance_Bond: require(ImagePath + 'Finance_Bond' + png),
  Finance_BondValueation: require(ImagePath + 'Finance_BondValueation' + png),
  Finance_CapitalStructure: require(ImagePath +
    'Finance_CapitalStructure' +
    png),
  Finance_CashFlow: require(ImagePath + 'Finance_CashFlow' + png),
  Finance_EMI: require(ImagePath + 'Finance_EMI' + png),
  Finance_IRR: require(ImagePath + 'Finance_IRR' + png),
  Finance_Lumpsum: require(ImagePath + 'Finance_Lumpsum' + png),
  Finance_Mortgage: require(ImagePath + 'Finance_Mortgage' + png),
  Finance_PPF: require(ImagePath + 'Finance_PPF' + png),
  Finance_SecurityMarket: require(ImagePath + 'Finance_SecurityMarket' + png),
  Finance_SimpleCompoundInterest: require(ImagePath +
    'Finance_SimpleCompoundInterest' +
    png),
  Finance_SIP: require(ImagePath + 'Finance_SIP' + png),
  Finance_SWP: require(ImagePath + 'Finance_SWP' + png),
  Finance_TVM: require(ImagePath + 'Finance_TVM' + png),

  Business_BCG: require(ImagePath + 'Business_BCG' + png),
  Business_Change: require(ImagePath + 'Business_Change' + png),
  Business_CostOfGoods: require(ImagePath + 'Business_CostOfGoods' + png),
  Business_GrossProfit: require(ImagePath + 'Business_GrossProfit' + png),
  Business_Product: require(ImagePath + 'Business_Product' + png),
  Business_Pyramid: require(ImagePath + 'Business_Pyramid' + png),
  Business_SWOT: require(ImagePath + 'Business_SWOT' + png),

  Stock_BullBear: require(ImagePath + 'Stock_BullBear' + png),
  Stock_Fibonacci: require(ImagePath + 'Stock_Fibonacci' + png),
  Stock_PE: require(ImagePath + 'Stock_PE' + png),
  Stock_Share: require(ImagePath + 'Stock_Share' + png),
  Stock_StockReturn: require(ImagePath + 'Stock_StockReturn' + png),
  Stock_TopDown: require(ImagePath + 'Stock_TopDown' + png),
};

export default Images;
