const ImagePath = '../Assets/Images/';
const png = '.png';

const Images = {
  True: require(ImagePath + 'True' + png),
  onboarding_0: require(ImagePath + 'onboarding_0' + png),
  onboarding_1: require(ImagePath + 'onboarding_1' + png),
  onboarding_2: require(ImagePath + 'onboarding_2' + png),
  Announcing: require(ImagePath + 'Announcing' + png),
  Notice: require(ImagePath + 'Notice' + png),
  OurPromise: require(ImagePath + 'OurPromise' + png),
  Safeguard: require(ImagePath + 'Safeguard' + png),
  Terms: require(ImagePath + 'Terms' + png),
  Afrikaans: require(ImagePath + 'Afrikaans' + png),
  Arabic: require(ImagePath + 'Arabic' + png),
  Bengali: require(ImagePath + 'Bengali' + png),
  Chinese: require(ImagePath + 'Chinese' + png),
  Danish: require(ImagePath + 'Danish' + png),
  Dutch: require(ImagePath + 'Dutch' + png),
  Filipino: require(ImagePath + 'Filipino' + png),
  US: require(ImagePath + 'US' + png),
  Logo: require(ImagePath + 'Logo' + png),
  PrivacyPolicy: require(ImagePath + 'PrivacyPolicy' + png),
  InviteFriends: require(ImagePath + 'InviteFriends' + png),
  RateUs: require(ImagePath + 'RateUs' + png),
  Back: require(ImagePath + 'Back' + png),
  Drawer: require(ImagePath + 'Drawer' + png),
  Home: require(ImagePath + 'Home' + png),
  AboutUs: require(ImagePath + 'AboutUs' + png),
  EmiCalculator: require(ImagePath + 'EmiCalculator' + png),

  AllCalculatorTheory: require(ImagePath + 'AllCalculatorTheory' + png),
  ATMFinder: require(ImagePath + 'ATMFinder' + png),
  BankFinder: require(ImagePath + 'BankFinder' + png),
  CompareLoans: require(ImagePath + 'CompareLoans' + png),
  CurrencyConversion: require(ImagePath + 'CurrencyConversion' + png),
  Discount: require(ImagePath + 'Discount' + png),
  ELS: require(ImagePath + 'ELS' + png),
  FAQ: require(ImagePath + 'FAQ' + png),
  FixedDeposit: require(ImagePath + 'FixedDeposit' + png),
  LoanEligibility: require(ImagePath + 'LoanEligibility' + png),
  LumpsumCalculator: require(ImagePath + 'LumpsumCalculator' + png),
  Margin: require(ImagePath + 'Margin' + png),
  MarginWithSales: require(ImagePath + 'MarginWithSales' + png),
  Markup: require(ImagePath + 'Markup' + png),
  OperatingMargin: require(ImagePath + 'OperatingMargin' + png),
  Price: require(ImagePath + 'Price' + png),
  PublicProvidentFund: require(ImagePath + 'PublicProvidentFund' + png),
  RecurringDeposit: require(ImagePath + 'RecurringDeposit' + png),
  SimpleCompound: require(ImagePath + 'SimpleCompound' + png),
  SIP: require(ImagePath + 'SIP' + png),
  SWP: require(ImagePath + 'SWP' + png),
  TaxCalculation: require(ImagePath + 'TaxCalculation' + png),
};

export default Images;
