const Strings = {
  onBoardingTitle1: 'Easy & Fast Calculate Your EMI',
  onBoardingText1:
    'Their EMI, contributing to a convenient and efficient financial planning experience.',
  onBoardingTitle2: 'Easiest Way Currency Converter',
  onBoardingText2:
    'Making it the most straight forward & convenient way to perform currency conversions, the emphasis is on simplicity & ease of use.',
  onBoardingTitle3: 'Strategic Financial Planning',
  onBoardingText3:
    'The app is presented as a valuable resource for those seeking to make informed and strategic financial decisions.',
  Terms: 'Terms',
  termsDesc:
    'By accessing this application, you are agreeing to be bound by the application terms of services terms of services & all applicable laws and regulation',
  OurPromise: 'Our Promise',
  OurPromiseDesc: `A promise that the service will be secure and we don't collect any kind of personal data & sensitive information from users.`,
  Safeguard: 'Safeguard',
  SafeguardDesc:
    'We would like to remind our users that using the app outside of its intended purpose and terms of use is a violation of our policies, and we reserve the right to restrict access to the app if such use is detected.',
  Announcing: 'Announcing',
  AnnouncingDesc:
    'Dear users, we would must inform you that when we have any updated in our terms and service to better reflect our commitment to protecting your privacy.',
  Notice: 'Notice',
  NoticeDesc:
    'Please note that making any modifications to the app or its components is strictly prohibited and any result in a violation of our terms of service.',
  TermsAndConditions: 'Terms And Conditions',
  PleaseCheckFor: 'Please check for accept terms of condition',
  Accept: 'Accept',
  SelectYourLanguage: 'Select Your Language',
  SelectYourLanguageDesc: 'You can change the language in app setting',
  WelcomeToThe: 'Welcome To The',
  LoanGolLoanEMICalculator: 'LoanGol - Loan EMI Calculator',
  LoanGolLoanEMICalculatorDesc1:
    'Calculate equated monthly instalments (EMI) for any kind of loan including home loans, car/auto loans, personal loans etc.',
  LoanGolLoanEMICalculatorDesc2:
    'The loan EMI calculator is a simple and easy-to-use financial calculator that can help you calculate your monthly instalments for car loans, and other types of loans.',
  StartApp: 'Start App',
  InviteFriends: 'Invite Friends',
  PrivacyPolicy: 'Privacy Policy',
  RateUs: 'Rate Us',
  LoanEMICalculator: 'Loan EMI Calculator',
  Home: 'Home',
  AboutUs: 'About Us',
  ShareThisApp: 'Share This App',
  LoanEligibility: 'Loan Eligibility',
  CompareLoans: 'Compare Loans',
  TaxCalculation: 'Tax Calculation',
  SystematicWithdrawalPlan: 'Systematic Withdrawal Plan',
  SystematicInvestmentPlan: 'Systematic Investment Plan',
  EquityLinkedSavingScheme: 'Equity Linked Saving Scheme',
  LumpsumCalculator: 'Lumpsum Calculator',
  FixedDeposit: 'Fixed Deposit',
  RecurringDeposit: 'Recurring Deposit',
  PublicProvidentFund: 'Public Provident Fund',
  SimpleAndCompound: 'Simple & Compound',
  CurrencyConversion: 'Currency Conversion',
  DiscountCalculator: 'Discount Calculator',
  PriceCalculator: 'Price Calculator',
  MarginCalculator: 'Margin Calculator',
  MarkupCalculator: 'Markup Calculator',
  OperatingMargin: 'Operating Margin',
  MarginWithSales: 'Margin With Sales',
  BankFinder: 'Bank Finder',
  ATMFinder: 'ATM Finder',
  AllCalculatorTheory: 'All Calculator Theory',
  FAQ: 'Frequently Asked Questions',
  EMICalculator: 'EMI Calculator',
  Easyandfastway: 'Easy and fast way to calculator your loan EMI',
  InvestmentCalculator: 'Investment Calculator',
  FinanceCalculator: 'Finance Calculator',
  BusinessCalculator: 'Business Calculator',
  BankAndATMFinder: 'Bank And ATM Finder',
  MoreOptions: 'More Options',
  CalculateNow: 'Calculate Now',
  EMI: 'EMI',
  SWP: 'SWP',
  SIP: 'SIP',
  EquityLinkedScheme: 'Equity Linked Scheme',
  Lumpsum: 'Lumpsum',
  Theory: 'Theory',
  ApplyLoan: 'Apply Loan',
  Year: 'Year',
  Month: 'Month',
  FirstEMI: 'First EMI:- ',
  PrincipalAmount: 'Principal Amount',
  Interest: 'Interest',
  max50perannum: '(max 50% per annum)',
  LoanTenure: 'Loan Tenure',
  max30yr: '(max 30yr)',
  max50yr: '(max 50%)',
  Calculate: 'Calculate',
  Statistic: 'Statistic',
  TotalInterest: 'Total Interest',
  TotalPrinciple: 'Total Principle',
  TotalPaymentPrincipleInterest: 'Total Payment (Principle + Interest)',
  LoanLastDate: 'Loan Last Date',
  EMIMonthlyPayment: 'EMI (Monthly Payment)',
  ShareResult: 'Share Result',
  ConvertPDF: 'Convert PDF',
  GrossMonthlyIncome: 'Gross Monthly Income',
  TotalMonthlyEMI: 'Total Monthly EMI',
  LoanAmount: 'Loan Amount',
  AnnualInterestRate: 'Annual Interest Rate',
  Tenure: 'Tenure',
  LoanAmountYouAreEligibleFor: 'Loan Amount You Are Eligible For',
  EMIYouAreEligibleFor: 'EMI You Are Eligible For',
  LoanEligibilityDesc: `Loan eligible is calculated using the FOIR system, thus can vary with different banks, it's the estimated calculation.`,
  Loan1: 'Loan 1',
  Loan2: 'Loan 2',
  Difference: 'Difference : ',
  TotalPaymentAmount: 'Total Payment Amount',
  Amount: 'Amount',
  RateOfTax: 'Rate Of Tax',
  GSTisAdded: 'GST is Added',
  NetAmount: 'Net Amount',
  GSTAmount: 'GST Amount',
  TotalAmount: 'Total Amount',
  InvestmentAmount: 'Investment Amount',
  ExpectedRateOfInterest: 'Expected Rate Of Interest',
  MonthlyWithdrawalAmount: 'Monthly Withdrawal Amount',
  TotalInvestmentAmount: 'Total Investment Amount',
  TotalInterestValue: 'Total Interest Value',
  MaturityDate: 'Maturity Date',
  MaturityValue: 'Maturity Value',
  RateOfInterest: 'Rate Of Interest',
  TypeOfInterest: 'Type Of Interest',
  MaturityAmount: 'Maturity Amount',
  CurrencyOfTheAmount: 'Currency Of The Amount',
  AmountInDifferentCurrency: 'Amount In Different Currency',
  Price: 'Price',
  DiscountPercentage: 'Discount (%)',
  MarkupPercentage: 'Markup (%)',
  MarginPercentage: 'Margin (%)',
  SalesTaxPercentage: 'Sales Tax (%)',
  DiscountPrice: 'Discount Price',
  SavedAmount: 'Saved Amount',
  Cost: 'Cost',
  GrossMargin: 'Gross Margin',
  Revenue: 'Revenue',
  Profit: 'Profit',
  OperatingIncome: 'Operating Income',
  NetPrice: 'Net Price',
  FAQ_Quesion_1: '1. What is Loan ?',
  FAQ_Quesion_2: '2. What purpose can it be used ?',
  FAQ_Quesion_3: '3. Which eligibility criteria for used ?',
  FAQ_Quesion_4: '4. How much can one borrow ?',
  FAQ_Quesion_5: '5. From which back institution should one borrow ?',
  FAQ_Quesion_6: '6. How do bank decide on the maximum loan amount ?',
  FAQ_Quesion_7: '7. What are the common rates for loan ?',
  Bank: 'Bank',
  Finance: 'Finance',
  Business: 'Business',
  Stock: 'Stock',
  Theory: 'Theory',
  CompareLoan: 'Compare Loan',
  FD: 'FD',
  RD: 'RD',
  Saving: 'Saving',
  LoanToDepositRatio: 'Loan To Deposit Ratio',
  CreditCardPayoff: 'Credit Card Payoff',
  Accounting: 'Accounting',
  TypesOfBanks: 'Types Of Banks',
  Auditing: 'Auditing',
  Loans: 'Loans',
  PPF: 'PPF',
  SimpleandCompoundInterest: 'Simple & Compound Interest',
  MortgageCalculator: 'Mortgage Calculator',
  TVMCalculator: 'TVM Calculator',
  BondCalculation: 'Bond Calculation',
  IRRCalculator: 'IRR Calculator',
  CashFlow: 'Cash Flow',
  BondValuation: 'Bond Valuation',
  SecurityMarketEfficiency: 'Security Market Efficiency',
  CapitalStructure: 'Capital Structure',
  GrossProfit: 'Gross Profit',
  CostOfGoodsSold: 'Cost Of Goods Sold',
  BCGMatrix: 'BCG Matrix',
  SWOTAnalysis: 'SWOT Analysis',
  ProductLifecycle: 'Product Lifecycle',
  ChangeCurve: 'Change Curve',
  PyramidOfResult: 'Pyramid Of Result',
  StockReturnsandCapitalGain: 'Stock Returns & Capital Gain',
  PERatio: 'PE Ratio',
  FibonacciLevel: 'Fibonacci Level',
  ShareMarket: 'Share Market',
  WhatIsBullandBearMarket: 'What Is Bull & Bear Market',
  TopDownBottomandMarket: 'Top Down Bottom & Market',
  US: 'United States (US)',
  Afrikaans: 'Afrikaans',
  Arabic: 'Arabic',
  Bengali: 'Bengali',
  Chinese: 'Chinese',
  Danish: 'Danish',
  Dutch: 'Dutch',
  Filipino: 'Filipino',
  Simple: 'Simple',
  Compound: 'Compound',
  INR: 'INR',
  Dollar: 'Dollar',
  Euro: 'Euro',
  Dihram: 'Dihram',
  Yen: 'Yen',
  Pound: 'Pound',
};

export default Strings;
