const Strings = {
  Signintoyouraccount: 'Sign in to your account',
  Letsgetstarted: `Let's get started`,
  EmailAddress: 'Email Address',
  dummyEmailAddress: 'john@gmail.com',
  dummyPassword: '********',
  Password: 'Password',
  ForgotPassword: 'Forgot Password',
  Login: 'Login',
  UploadFiles: 'Upload Files',
  UploadFile: 'Upload File',
  UploadFilesDesc:
    'Allowed Extensions are PDF, JPG, PNG, GIF, DOC, DOCX, XLS, XLSX, PPT, PPTX, ZIP, RAR, MP4, Wmv, MSG.',
  UploadDate: 'Upload Date',
  Delete: 'Delete',
  ForgotPasswordDesc: `No worries, we'll send you rest instructions.`,
  MaxFilesize: 'Max File size is 05 MB.',
  SendEmail: 'Send Email',
  EmployeeName: 'Employee Name',
  VerifyYourCode: 'Verify Your Code',
  EnterCode: 'Enter Code',
  VerifyYourCodeDesc: `Enter your verification code that we sent you through your e-mail.`,
  Verify: 'Verify',
  ViewAll: 'View All',
  ViewProfile: 'View Profile',
  City: 'City',
  Rememberme: 'Remember me',
  ResponsibleEmployees: 'Responsible Employees',
  SelectEntity: 'Select Entity',
  NewBusiness: 'New Business',
  Name: 'Name',
  Archive: 'Archive',
  Commission: 'Commission',
  Principal: 'Principal',
  ProductionCapacity: 'Production Capacity',
  ApproxDesc:
    'Approx. 0% or 0 mt of 550.000 mt (0 out of 6) are currently performed.',
  Exptednoofdeliv: 'Expted no. of deliv',
  DeliveryPeriod: 'Delivery Period',
  ExportQty: 'Export Qty',
  Exptedavgmrg: 'Expted avg. mrg/t',
  OtherInformation: 'Other Information',
  JanuarytoDecember: 'January - December',
  CommenceDate: 'Commence Date',
  Exptdavgrev: 'Exptd avg. rev./t',
  Selected: 'Selected',
  Enterinformation: 'Enter information',
  ieoptionsriskadjustmentEtc: '(i.e. options, risk adjustment, Etc..)',
  NotSelected: 'Not Selected',
  DischargingPort: 'Discharging Port',
  ResetYourPassword: 'Reset Your Password',
  ResetYourPasswordDesc: `Enter your new password for you account.`,
  ReenterPassword: 'Re-enter Password',
  SetPassword: 'Set Password',
  EditProfile: 'Edit Profile',
  EditUserProfile: 'Edit User Profile',
  deleteTitle: 'Storage Admin User Rights',
  deleteTitleDesc: 'Are sure you want to delete storage admin user?',
  AddNewUser: 'Add New User',
  Add: 'Add',
  Email: 'Email',
  Save: 'Save',
  SelectUserRights: 'Select User Rights',
  SearchEntity: 'Search Entity',
  Searchhere: 'Search here',
  Language: 'Language',
  Security: 'Security',
  ProfilePhoto: 'Profile Photo',
  AddEntitiesandRights: 'Add Entities & Rights',
  FullName: 'FullName',
  Reset: 'Reset',
  PeterParker: 'Peter Parker',
  Peter: 'Peter',
  EntitieName: 'Entitie Name',
  Userlist: 'User list',
  LatestNewUser: 'Latest New User',
  AllUserList: 'All User List',
  Alluser: 'All user',
  Filter: 'Filter',
  UserRights: 'User Rights',
  PleaseSelect: 'Please Select',
  Entities: 'Entities',
  ShortName: 'Short Name',
  UserName: 'User Name',
  Apply: 'Apply',
  Productlist: 'Product list',
  MinePit: 'Mine/Pits',
  LatestProductList: 'Latest Product List',
  ViewProduct: 'View Product',
  AllProductList: 'All Product List',
  AllProduct: 'All Product',
  Partner: 'Partner',
  Region: 'Region',
  SpecType: 'Spec. Type',
  Country: 'Country',
  BusinessList: 'Business List',
  LatestBusinessList: 'Latest Business List',
  ViewBusiness: 'View Business',
  AllBusinessList: 'All Business List',
  AllBusiness: 'All Business',
  DischargeCountryLoadingCountry: 'Discharge Country / Loading Country',
  Employee: 'Employee',
  MinePitList: 'Mine/Pit List',
  LatestMinePitsList: 'Latest Mine/Pits List',
  ViewMine: 'View Mine',
  UserProfile: 'User Profile',
  EntitiesandRights: 'Entities & Rights',
  Users: 'Users',
  Products: 'Products',
  Businesses: 'Businesses',
  Contracts: 'Contracts',
  Deliveries: 'Deliveries',
  Storage: 'Storage',
  Invoicing: 'Invoicing',
  KnMgmt: 'Kn. Mgmt.',
  Templates: 'Templates',
  StandingData: 'Standing Data',
  Modules: 'Modules',
  DBAdmin: 'DB Admin',
  Archive: 'Archive',
  Reports: 'Reports',
  Settings: 'Settings',
};

export default Strings;
